// Code generated by MockGen. DO NOT EDIT.
// Source: account_domain.go

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	context "context"
	reflect "reflect"
	model "spider-go/model"

	gomock "github.com/golang/mock/gomock"
)

// MockAccountRepository is a mock of AccountRepository interface.
type MockAccountRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAccountRepositoryMockRecorder
}

// MockAccountRepositoryMockRecorder is the mock recorder for MockAccountRepository.
type MockAccountRepositoryMockRecorder struct {
	mock *MockAccountRepository
}

// NewMockAccountRepository creates a new mock instance.
func NewMockAccountRepository(ctrl *gomock.Controller) *MockAccountRepository {
	mock := &MockAccountRepository{ctrl: ctrl}
	mock.recorder = &MockAccountRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountRepository) EXPECT() *MockAccountRepositoryMockRecorder {
	return m.recorder
}

// CreateAccout mocks base method.
func (m *MockAccountRepository) CreateAccout(ctx context.Context, acc model.Account) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccout", ctx, acc)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAccout indicates an expected call of CreateAccout.
func (mr *MockAccountRepositoryMockRecorder) CreateAccout(ctx, acc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccout", reflect.TypeOf((*MockAccountRepository)(nil).CreateAccout), ctx, acc)
}

// FindAccountByUsername mocks base method.
func (m *MockAccountRepository) FindAccountByUsername(ctx context.Context, username string) (*model.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAccountByUsername", ctx, username)
	ret0, _ := ret[0].(*model.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAccountByUsername indicates an expected call of FindAccountByUsername.
func (mr *MockAccountRepositoryMockRecorder) FindAccountByUsername(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAccountByUsername", reflect.TypeOf((*MockAccountRepository)(nil).FindAccountByUsername), ctx, username)
}
